### ISSUE TITLE
Raid Browser Listing

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#164]
Cannot list name in Raid Browser for raid dungeons.

**Comment by Zyres** [comment]
How does it look like when you open it? Please provide more information....
I'm happy seeing people testing the stuff and reporting issues, but give us MORE information when you create an issue...

**Comment by Nupper** [comment]
It all looks standard even with the custom raids i've added. but you select the raid and click "List my name" the name dose not show even after being refreshed and Damage, Tank or Healer is selected. they are pretty much dead buttons in away.

**Comment by Zyres** [comment]
This?
![2015-10-21_22-34-50](https://cloud.githubusercontent.com/assets/8825392/10649383/14e486f0-7844-11e5-9645-aa2c13dee661.jpg)

**Comment by Nupper** [comment]
Yes pretty much

**Comment by aaron02** [comment]
I take a look at it currently i fixed random lfg issue and showing items

**Comment by Zyres** [comment]
@aaron02 :+1:

**Comment by Nupper** [comment]
LFG dose not show items as i put that in another commit

**Comment by aaron02** [comment]
Yeah i fixed this i just ned to make a pull request

**Comment by Nupper** [comment]
ah ok...an idea with the database option to change items.

**Comment by Zyres** [comment]
@aaron02 and @Razfury is this still a valid issue, I got the feeling this is fixed long time ago?

**Comment by aaron02** [comment]
not fixed. this is still a missing future. Raid Browser is not supported at all ( 3.3.5 / 4.3.4 )
